// src/lib/player/MediaSelection.svelte
<script lang="ts">
	import { onMount, tick } from 'svelte';
	import { PUBLIC_BE } from '$env/static/public';
	import CaretSort from 'svelte-radix/CaretSort.svelte';
	import { IconCheck, IconChevronRight } from '@tabler/icons-svelte';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Popover from '$lib/components/ui/popover/index.js';
	import * as Command from '$lib/components/ui/command/index.js';
	import {
		getTitleComponentsByJobs,
		type Job,
		preprocessJobs
	} from '$lib/player/t';
	import { goto } from '$app/navigation';
	import TitlePoster from '$lib/player/TitlePoster.svelte';

	export let data: { jobs: Job[], job: Job | undefined };
	let { jobs, job } = data;

	export let bounceToOverride: ((_id: string) => void) | null = null;
	let titleSelectionOpen = false;
	let seSelectionOpen = false;
	let selectedTitleId: string | undefined = job?.Title?.titleId;
	let selectedSe: string | undefined = job?.Title?.episode?.se;
	$: titles = getTitleComponentsByJobs(jobs);
	$: selected = selectedTitleId ? titles[selectedTitleId] : null;
	$: selectedEpisode = selected?.episodes?.find((ep) => ep.se === selectedSe);
	$: newJobs = getNewJobs(jobs);

	function getNewJobs(jobs: Job[]): Job[] {
		const last6 = jobs.sort((a, b) => {
			return a.JobModTime > b.JobModTime ? -1 : 1;
		}).slice(0, 6);
		const last3Days = jobs.filter((job) => {
			const diff = Date.now() - job.JobModTime * 1000;
			return diff < 1000 * 60 * 60 * 24 * 3;
		});
		const results: { [key: string]: Job } = {};
		for (const job of last3Days) {
			results[job.Id] = job;
		}
		for (const job of last6) {
			results[job.Id] = job;
		}
		return Object.values(results);
	}

	function bounceTo(id: string) {
		if (bounceToOverride) {
			bounceToOverride(id);
		} else {
			goto(`/${id}`);
		}
	}

	export function updateList(untilId: string | null = null, onSuccess =
		(_1: Job[]) => {
		}) {
		if (untilId !== null && jobs.find((job) => job.Id === untilId)) {
			onSuccess(jobs);
			return;
		}
		fetch(`${PUBLIC_BE}/all`)
			.then(response => response.json())
			.then(data => {
				if (data?.length > 0) {
					jobs = preprocessJobs(data);
					console.log('updated jobs', jobs);
					onSuccess(jobs);
				}
			});
	}

	onMount(() => {
		const ii = setInterval(() => {
			updateList();
		}, 60000);
		return () => {
			clearInterval(ii);
		};
	});
</script>
<div
	class="md:grid md:grid-cols-[minmax(0,1fr)_min-content_minmax(0,1fr)] max-md:flex gap-2 items-center justify-center max-md:flex-col w-full">
	<Popover.Root bind:open={titleSelectionOpen}>
		<Popover.Trigger asChild let:builder>
			<Button
				builders={[builder]}
				variant="outline"
				role="combobox"
				aria-expanded={titleSelectionOpen}
				class="max-md:w-full justify-between font-semibold {!selected?.episodes ? 'col-span-3' : ''}">
			<span class="max-w-[calc(100%-2rem)] text-ellipsis overflow-hidden">
				{selected?.title || "Select media"}
			</span>
				<CaretSort class="ml-2 h-4 w-4 shrink-0 opacity-50" />
			</Button>
		</Popover.Trigger>
		<Popover.Content align="start" class="p-0 w-auto">
			<Command.Root>
				<Command.Input placeholder="Search title..." class="h-9" />
				<Command.Empty>No title found.</Command.Empty>
				<Command.Group class="overflow-y-auto max-h-[37vh]">
					{#each Object.values(titles) as title}
						<Command.Item class="p-1 {selectedTitleId === title.titleId ? 'font-bold' : ''}" value={title.title}
													onSelect={()=>{
											titleSelectionOpen = false;
									selectedTitleId = title.titleId;
									selectedSe = undefined;
									if(!title.episodes) {
										bounceTo(title.id)
									}else{
										tick().then(() => {
    							  seSelectionOpen = true;
    								});
									}
						}}>
							<TitlePoster title={title.rep ? title.rep :
							title.episodes ? title.episodes[0] : title
							} isNew={
							newJobs.find((job) => job.Title.titleId === title.titleId) !== undefined
							}/>
							<span class="mr-4">{title.title}</span>
							<IconCheck size={18} stroke={2}
												 class='ml-auto right-0 {selectedTitleId === title.titleId ? "" : "text-transparent"}'
							/>
						</Command.Item>
					{/each}
				</Command.Group>
			</Command.Root>
		</Popover.Content>
	</Popover.Root>
	{#if selected?.episodes}
		<IconChevronRight
			class="max-md:hidden"
			size={20} stroke={2} />

		<Popover.Root bind:open={seSelectionOpen}>
			<Popover.Trigger asChild let:builder>
				<Button
					builders={[builder]}
					variant="outline"
					role="combobox"
					aria-expanded={titleSelectionOpen}
					class="max-md:w-full justify-between font-semibold {!selectedSe ? 'text-red-600 font-bold' : ''}"
				>
										<span class="max-w-[calc(100%-2rem)] text-ellipsis overflow-hidden">{selectedEpisode ?
											`${selectedSe} - ${selectedEpisode.title}` : "Select episode"}</span>
					<CaretSort class="ml-2 h-4 w-4 shrink-0 opacity-50" />
				</Button>
			</Popover.Trigger>
			<Popover.Content align="start" class="p-0 w-auto">
				<Command.Root>
					<Command.Input placeholder="Search episode..." class="h-9" />
					<Command.Empty>No episode found.</Command.Empty>
					<Command.Group class="overflow-y-auto max-h-[37vh]">
						{#each selected.episodes as es}
							<Command.Item class="p-1 {selectedSe === es.se ? 'font-bold' : ''}" value={es.se + "-" + es.title}
														onSelect={()=>{
									seSelectionOpen = false;
									bounceTo(es.id)
									selectedSe = es.se;
						}}>
									<TitlePoster title={es} isNew={newJobs.find((job) => job.Id === es.id) !== undefined} />
								<span class="mr-4">{es.se} - {es.title}</span>
								<IconCheck size={18} stroke={2}
													 class='ml-auto right-0 {selectedSe === es.se ? "" : "text-transparent"}'
								/>
							</Command.Item>
						{/each}
					</Command.Group>
				</Command.Root>
			</Popover.Content>
		</Popover.Root>
	{/if}
</div>

// components/player/MediaSelection.tsx
"use client";

import { forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { IconCheck, IconChevronRight, IconChevronDown } from '@tabler/icons-react';
import { PUBLIC_BE } from '@/lib/env';
import { Button } from '@/components/ui/button';
import * as Popover from '@/components/ui/popover';
import * as Command from '@/components/ui/command';
import { TitlePoster } from '@/components/player/TitlePoster';
import { getTitleComponentsByJobs, type Job, preprocessJobs } from '@/lib/player/t';

export type MediaSelectionHandle = {
	updateList: (_untilId?: string | null, _onSuccess?: (_jobs: Job[]) => void) => void;
};

export const MediaSelection = forwardRef<
	MediaSelectionHandle,
	{
		data: { jobs: Job[]; job?: Job | undefined };
		bounceToOverride?: ((_id: string) => void) | null;
	}
>(function MediaSelection({ data, bounceToOverride = null }, ref) {
	const router = useRouter();
	const [jobs, setJobs] = useState<Job[]>(data.jobs);
	const [titleSelectionOpen, setTitleSelectionOpen] = useState(false);
	const [seSelectionOpen, setSeSelectionOpen] = useState(false);
	const [selectedTitleId, setSelectedTitleId] = useState<string | undefined>(data.job?.Title?.titleId);
	const [selectedSe, setSelectedSe] = useState<string | undefined>(data.job?.Title?.episode?.se);

	useEffect(() => {
		setJobs(data.jobs);
	}, [data.jobs]);

	useEffect(() => {
		setSelectedTitleId(data.job?.Title?.titleId);
		setSelectedSe(data.job?.Title?.episode?.se);
	}, [data.job]);

	const titles = useMemo(() => getTitleComponentsByJobs(jobs), [jobs]);
	const selected = selectedTitleId ? titles[selectedTitleId] : null;
	const selectedEpisode = selected?.episodes?.find((episode) => episode.se === selectedSe);
	const newJobs = useMemo(() => getNewJobs(jobs), [jobs]);

	function getNewJobs(jobs: Job[]): Job[] {
		const last7 = jobs
			.slice()
			.sort((a, b) => (a.JobModTime > b.JobModTime ? -1 : 1))
			.slice(0, 7);
		const last3Days = jobs.filter((job) => {
			const diff = Date.now() - job.JobModTime * 1000;
			return diff < 1000 * 60 * 60 * 24 * 7;
		});
		const results: Record<string, Job> = {};
		for (const next of last3Days) {
			results[next.Id] = next;
		}
		for (const next of last7) {
			results[next.Id] = next;
		}
		return Object.values(results);
	}

	function bounceTo(id: string) {
		if (bounceToOverride) {
			bounceToOverride(id);
		} else {
			router.push(`/${id}`);
		}
	}

	const updateList = useCallback((untilId: string | null = null, onSuccess: (_jobs: Job[]) => void = () => {}) => {
		if (untilId !== null && jobs.find((candidate) => candidate.Id === untilId)) {
			onSuccess(jobs);
			return;
		}
		fetch(`${PUBLIC_BE}/all`)
			.then((response) => response.json())
			.then((payload) => {
				if (payload?.length > 0) {
					const nextJobs = preprocessJobs(payload);
					setJobs(nextJobs);
					onSuccess(nextJobs);
				}
			});
	}, [jobs]);

	useImperativeHandle(ref, () => ({ updateList }), [updateList]);

	useEffect(() => {
		const timer = window.setInterval(() => {
			updateList();
		}, 60000);
		return () => window.clearInterval(timer);
	}, [updateList]);

	return (
		<div className="md:grid md:grid-cols-[minmax(0,1fr)_min-content_minmax(0,1fr)] max-md:flex max-md:flex-col items-center justify-center gap-2 w-full">
			<Popover.Root open={titleSelectionOpen} onOpenChange={setTitleSelectionOpen}>
				<Popover.Trigger asChild>
					<Button
						variant="outline"
						role="combobox"
						aria-expanded={titleSelectionOpen}
						className={`max-md:w-full justify-between font-semibold ${!selected?.episodes ? 'col-span-3' : ''}`}
					>
						<span className="max-w-[calc(100%-2rem)] overflow-hidden text-ellipsis">{selected?.title || 'Select media'}</span>
						<IconChevronDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
					</Button>
				</Popover.Trigger>
				<Popover.Content align="start" className="w-auto p-0">
					<Command.Root>
						<Command.Input placeholder="Search title..." className="h-9" />
						<Command.Empty>No title found.</Command.Empty>
						<Command.Group className="max-h-[37vh] overflow-y-auto">
							{Object.values(titles).map((title) => (
								<Command.Item
									key={title.titleId}
									className={`p-1 ${selectedTitleId === title.titleId ? 'font-bold' : ''}`}
									value={title.title}
									onSelect={() => {
										setTitleSelectionOpen(false);
										setSelectedTitleId(title.titleId);
										setSelectedSe(undefined);
										if (!title.episodes) {
											bounceTo(title.id);
										} else {
											window.setTimeout(() => {
												setSeSelectionOpen(true);
											}, 0);
										}
									}}
								>
									<TitlePoster title={title.rep ? title.rep : title.episodes ? title.episodes[0] : title} isNew={newJobs.find((candidate) => candidate.Title.titleId === title.titleId) !== undefined} />
									<span className="mr-4">{title.title}</span>
									<IconCheck
										size={18}
										stroke={2}
										className={`ml-auto right-0 ${selectedTitleId === title.titleId ? '' : 'text-transparent'}`}
									/>
								</Command.Item>
							))}
						</Command.Group>
					</Command.Root>
					</Popover.Content>
				</Popover.Root>

			{selected?.episodes ? (
				<>
					<IconChevronRight className="max-md:hidden" size={20} stroke={2} />

					<Popover.Root open={seSelectionOpen} onOpenChange={setSeSelectionOpen}>
						<Popover.Trigger asChild>
							<Button
								variant="outline"
								role="combobox"
								aria-expanded={titleSelectionOpen}
								className={`max-md:w-full justify-between font-semibold ${!selectedSe ? 'font-bold text-red-600' : ''}`}
							>
								<span className="max-w-[calc(100%-2rem)] overflow-hidden text-ellipsis">
									{selectedEpisode ? `${selectedSe} - ${selectedEpisode.title}` : 'Select episode'}
								</span>
								<IconChevronDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
							</Button>
						</Popover.Trigger>
						<Popover.Content align="start" className="w-auto p-0">
							<Command.Root>
								<Command.Input placeholder="Search episode..." className="h-9" />
								<Command.Empty>No episode found.</Command.Empty>
								<Command.Group className="max-h-[37vh] overflow-y-auto">
									{selected.episodes.map((episode) => (
										<Command.Item
											key={episode.id}
											className={`p-1 ${selectedSe === episode.se ? 'font-bold' : ''}`}
											value={`${episode.se}-${episode.title}`}
											onSelect={() => {
												setSeSelectionOpen(false);
												bounceTo(episode.id);
												setSelectedSe(episode.se);
											}}
										>
											<TitlePoster title={episode} isNew={newJobs.find((candidate) => candidate.Id === episode.id) !== undefined} />
											<span className="mr-4">{episode.se} - {episode.title}</span>
											<IconCheck size={18} stroke={2} className={`ml-auto right-0 ${selectedSe === episode.se ? '' : 'text-transparent'}`} />
										</Command.Item>
									))}
								</Command.Group>
							</Command.Root>
						</Popover.Content>
					</Popover.Root>
				</>
			) : null}
		</div>
	);
});
