// src/lib/player/MoveToast.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Button } from '$lib/components/ui/button';
	import TitlePoster from '$lib/player/TitlePoster.svelte';
	import { type Job, type Player } from '$lib/player/t';
	import { goto } from '$app/navigation';
	import Pfp from '$lib/player/Pfp.svelte';
	export let historicalPlayers: { [key: string]: Player };
	export let seconds:number;
	export let firedBy: Player;
	export let job: Job | undefined;
	let closed = false;

	onMount(() => {
		const interval = setInterval(() => {
			seconds--;
			if (seconds === 0) {
				clearInterval(interval);
				if(job?.Id){
					goto(`/${job?.Id}`)
				}
			}
		}, 1000);
		return () => clearInterval(interval);
	});
</script>


{#if !closed}
	<Card.Root class="w-full">
		<Card.Header>
			<Card.Title class="flex items-center">
				{#if firedBy?.id}
					<Pfp id={firedBy?.id} class="avatar mr-2"
							 discordUser={historicalPlayers[firedBy?.id]?.discordUser}/>
				{/if}
				{#if seconds > 0}
				<span>Moving in {seconds} second{seconds > 1 ? "s" : ""}</span>
			{:else}
				<span>Moving...</span>
			{/if}
			</Card.Title>
		</Card.Header>
		<Card.Content>
			<div class="flex gap-1 items-center w-full text-sm font-normal">
				{#if job?.Title}
					<TitlePoster title={job.Title}/>
				{/if}
				To: {job?.Input}</div>
		</Card.Content>
		<Card.Footer class="flex justify-between">
			<Button variant="outline">
				By: {firedBy?.name}
				</Button>
			<Button variant="default"
			on:click={() => closed = true}
			>Close</Button>
		</Card.Footer>
	</Card.Root>
{/if}

// components/player/MoveToast.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Job, Player } from '@/lib/player/t';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Pfp } from '@/components/player/Pfp';
import { TitlePoster } from '@/components/player/TitlePoster';

export function MoveToast({
	historicalPlayers,
	seconds,
	firedBy,
	job,
	onClose,
	staticBaseUrl
}: {
	historicalPlayers: Record<string, Player>;
	seconds: number;
	firedBy: Player;
	job: Job | undefined;
	onClose: () => void;
	staticBaseUrl: string;
}) {
	const router = useRouter();
	const [remaining, setRemaining] = useState(seconds);

	useEffect(() => {
		if (remaining <= 0) {
			if (job?.Id) {
				router.push(`/${job.Id}`);
			}
			return;
		}
		const interval = setInterval(() => {
			setRemaining((value) => value - 1);
		}, 1000);
		return () => clearInterval(interval);
	}, [job?.Id, remaining, router]);

	return (
		<Card className="w-full">
			<CardHeader>
				<CardTitle className="flex items-center">
					{firedBy?.id ? (
						<Pfp
							id={firedBy.id}
							className="avatar mr-2"
							discordUser={historicalPlayers[firedBy.id]?.discordUser}
							staticBaseUrl={staticBaseUrl}
						/>
					) : null}
					{remaining > 0 ? (
						<span>
							Moving in {remaining} second{remaining > 1 ? 's' : ''}
						</span>
					) : (
						<span>Moving...</span>
					)}
				</CardTitle>
			</CardHeader>
			<CardContent>
				<div className="flex w-full items-center gap-1 text-sm font-normal">
					{job?.Title ? <TitlePoster title={job.Title} staticBaseUrl={staticBaseUrl} /> : null}
					To: {job?.Input}
				</div>
			</CardContent>
			<CardFooter className="flex justify-between">
				<Button variant="outline">By: {firedBy?.name}</Button>
				<Button variant="default" onClick={onClose}>
					Close
				</Button>
			</CardFooter>
		</Card>
	);
}
